# NumPy 

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries.

## Installation Instructions

**It is highly recommended you install Python using the Anaconda distribution to make sure all underlying dependencies (such as Linear Algebra libraries) all sync up with the use of a conda install. If you have Anaconda, install NumPy by going to your terminal or command prompt and typing:**
    
    conda install numpy


In [1]:
pip install numpy

#install pip

SyntaxError: invalid syntax (<ipython-input-1-0bd5776349e8>, line 1)

## Using NumPy

In [4]:
import numpy as np

Numpy has many built-in functions and capabilities. 
Important aspects of Numpy: vectors,arrays,matrices, and number generation. 
# Numpy Arrays

 Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).


## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [5]:
my_list = [1,2,3]
#print(type(my_list))

s = "10"
a = int(s)
print(type(a))

<class 'int'>


In [8]:
x = np.array(my_list)
x.shape

(3,)

In [9]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix
print(type(my_matrix))

#print(my_matrix.shape)

<class 'list'>


In [12]:
x = np.array(my_matrix)
print(x.shape)

(3, 3)


In [13]:
my_mat = [[[1,2,3],[3,4,5],[5,6,7]],[[1,2,3],[3,4,5],[5,6,7]],[[1,2,3],[3,4,5],[5,6,7]]]
print(np.array(my_mat).shape)
my_mat


(3, 3, 3)


[[[1, 2, 3], [3, 4, 5], [5, 6, 7]],
 [[1, 2, 3], [3, 4, 5], [5, 6, 7]],
 [[1, 2, 3], [3, 4, 5], [5, 6, 7]]]

In [15]:
x = [1,2,3]
x = np.array(x)
x.shape

#one row containing 3 elements

(3,)

In [25]:
x = [[[1,2,3]]]
x = np.array(x)
x.shape

#one row n 3 columns

(1, 1, 3)

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [31]:
np.arange(2,20)

#start = 0
#stop = 20 (exclusive)
#step = 1

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [32]:
np.arange(0,12,2)

array([ 0,  2,  4,  6,  8, 10])

In [33]:
np.arange(10 , 0 , -3)

array([10,  7,  4,  1])

In [34]:
np.arange(0 , 40 ,4)

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36])

### zeros and ones

Generate arrays of zeros or ones

In [ ]:
print(np.zeros(3 ).shape)

In [39]:
np.zeros((5,5,9,4 ,4))

array([[[[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         ...,

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]],


        [[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 

In [38]:
import numpy as np
np.zeros((2 , 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [35]:
np.ones(3)

array([1., 1., 1.])

In [37]:
np.ones((3,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

### linspace
Return evenly spaced numbers over a specified interval.

In [44]:
np.linspace(2 , 4,3,endpoint= False)

array([2.        , 2.66666667, 3.33333333])

In [45]:

np.linspace(0,10,4 ,endpoint= False ,retstep = True)

(array([0. , 2.5, 5. , 7.5]), 2.5)

In [46]:
np.linspace(0,10,3, endpoint = False)

array([0.        , 3.33333333, 6.66666667])

## eye

Creates an identity matrix

In [52]:
np.eye(4,5, -1)

#AI = A

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [ ]:
np.eye(5 , 4 , -2)

In [ ]:
np.eye(5 , 8 , -2)

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [53]:
np.random.rand(10)

array([0.87398628, 0.47902378, 0.2179993 , 0.17887391, 0.20039669,
       0.5039534 , 0.2029195 , 0.64980313, 0.97749698, 0.41496533])

In [54]:
np.random.rand(2,2)

array([[0.84794278, 0.93485239],
       [0.87332102, 0.21141972]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [55]:
np.random.randn(2)

array([0.55855592, 0.74158916])

In [56]:
np.random.randn(5,5)

array([[ 1.65207613,  0.45685646, -1.01595212, -1.43386744,  1.12919788],
       [ 1.94555653, -0.087859  ,  0.80904329, -0.59306216, -0.23245152],
       [-0.12875973, -2.74994018,  0.91103162, -3.13022547, -0.0989989 ],
       [ 0.74132977,  0.16598027,  1.73406968,  0.30573764,  0.32187779],
       [-1.02382833,  0.15706583, -0.09032053, -0.08270159, -0.8204391 ]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [60]:
np.random.randint(1,100)

81

In [61]:
np.random.randint(1,100,10)

array([38, 67, 47, 34,  9, 10, 17, 60, 38, 64])

In [63]:
#Question : Print 13 random values from 22 t0 56
np.random.randint(22,57,13)

array([44, 27, 53, 28, 35, 48, 54, 46, 25, 50, 37, 24, 42])

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [64]:
arr = np.arange(25)
#ranarr = np.random.randint(0,50,10) 

In [65]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [66]:
print(arr.shape)

(25,)


In [ ]:
ranarr

## Reshape
Returns an array containing the same data with a new shape.

In [70]:
print(arr1.shape)
print(arr1)

(25, 1)
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]
 [24]]


In [71]:
arr1 =arr.reshape(5,4)

ValueError: cannot reshape array of size 25 into shape (5,4)

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [72]:
import numpy as np
ranarr = np.random.randint(0,50,10) 
ranarr

array([26,  7, 15,  9, 25, 44, 15, 33, 47, 42])

In [73]:
ranarr.max()

47

In [74]:
ranarr.argmax()

8

In [75]:
ranarr.min()

7

In [76]:
ranarr.argmin()

1

## Shape

Shape is an attribute that arrays have (not a method):

In [ ]:
arr

In [ ]:
# Vector
arr.shape

In [ ]:
# Notice the two sets of brackets
arr.reshape(1,25)


In [ ]:
arr.reshape(1,25).shape

In [ ]:
arr.reshape(25,1)


In [ ]:
arr.reshape(25,1).shape

### dtype

You can also grab the data type of the object in the array:

In [77]:
arr.dtype

dtype('int32')

In [78]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
import pandas as pd

In [ ]:
df = pd.DataFrame({"Name": ["Braund, Mr. Owen Harris","Allen, Mr. William Henry","Bonnell, Miss. Elizabeth",],
         "Age": [22, 35, 58],
          "Sex": ["male", "male", "female"],
      }
   )

In [ ]:
df

In [ ]:
df["Name"]

In [ ]:
df["Age"].min()

In [ ]:


matplotlib
pandas
numpy