# NumPy Operations

## Arithmetic

You can easily perform array with array arithmetic, or scalar with array arithmetic. Let's see some examples:

In [1]:
import numpy as np
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:

arr1 = arr + arr
arr1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [3]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [4]:
arrr1 =arr - arr
print(arrr1)

[0 0 0 0 0 0 0 0 0 0]


In [5]:
5/0

ZeroDivisionError: division by zero

In [6]:
# Warning on division by zero, but not an error!
# Just replaced with nan
arrr1/arrr1


<ipython-input-6-971b0e51712e>:3: RuntimeWarning: invalid value encountered in true_divide
  arrr1/arrr1


array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

In [ ]:
arr

In [7]:
# Also warning, but not an error instead infinity
1/arr


<ipython-input-7-c81c9b6169c9>:2: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [ ]:
arr**0.5


## Universal Array Functions

Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones:

In [ ]:
arr



In [ ]:
#Taking Square Roots
np.sqrt(arr)

In [ ]:
#Calcualting exponential (e^)
np.exp(arr)

In [ ]:
np.amax(arr) #same as arr.max()

In [ ]:
np.sin(arr)

In [ ]:
np.log(arr)

In [ ]:
for i in range(10):
    print(i)